type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2010": [
    { title: "星际争霸2：自由之翼", score: 9.2 },
    { title: "红色警戒3：起义时刻", score: 8.0 },
    { title: "质量效应2", score: 9.4 },
    { title: "神秘海域2：纵横四海", score: 9.5 },
    { title: "使命召唤：黑色行动", score: 8.7 },
    { title: "刺客信条：兄弟会", score: 8.8 },
    { title: "超级马里奥银河2", score: 9.7 },
    { title: "生化危机5", score: 8.5 },
    { title: "文明5", score: 9.1 },
    { title: "极品飞车：热力追踪", score: 8.3 },
    { title: "战神3", score: 9.3 },
    { title: "辐射：新维加斯", score: 9.0 },
  ],
  "2011": [
    { title: "上古卷轴5：天际", score: 9.5 },
    { title: "传送门2", score: 9.6 },
    { title: "战地3", score: 8.9 },
    { title: "使命召唤：现代战争3", score: 8.5 },
    { title: "蝙蝠侠：阿卡姆之城", score: 9.4 },
    { title: "黑暗之魂", score: 9.3 },
    { title: "神秘海域3：德雷克的诡计", score: 9.2 },
    { title: "杀手：赦免", score: 8.7 },
    { title: "死亡空间2", score: 9.0 },
    { title: "极品飞车：亡命天涯", score: 8.6 },
    { title: "FIFA 12", score: 9.0 },
    { title: "NBA 2K12", score: 8.8 },
  ],
  "2012": [
    { title: "刺客信条3", score: 8.5 },
    { title: "无主之地2", score: 9.2 },
    { title: "光环4", score: 9.0 },
    { title: "质量效应3", score: 8.9 },
    { title: "使命召唤：黑色行动2", score: 8.7 },
    { title: "极限竞速：地平线", score: 9.1 },
    { title: "生化危机6", score: 7.9 },
    { title: "远哭3", score: 8.8 },
    { title: "暗黑破坏神3", score: 8.5 },
    { title: "波斯王子：重生", score: 8.3 },
    { title: "FIFA 13", score: 9.0 },
    { title: "NBA 2K13", score: 8.9 },
  ],
  "2013": [
    { title: "最后生还者", score: 9.7 },
    { title: "侠盗猎车手5", score: 9.6 },
    { title: "生化奇兵：无限", score: 9.4 },
    { title: "古墓丽影：重启", score: 9.1 },
    { title: "战神：升天", score: 8.8 },
    { title: "超级马里奥3D世界", score: 9.3 },
    { title: "刺客信条4：黑旗", score: 8.9 },
    { title: "战地4", score: 8.7 },
    { title: "使命召唤：幽灵", score: 8.4 },
    { title: "地铁：最后的曙光", score: 8.9 },
    { title: "FIFA 14", score: 8.8 },
    { title: "NBA 2K14", score: 8.7 },
  ],
  "2014": [
    { title: "龙腾世纪：审判", score: 9.0 },
    { title: "命运", score: 8.5 },
    { title: "黑暗之魂2", score: 9.1 },
    { title: "使命召唤：高级战争", score: 8.6 },
    { title: "刺客信条：大革命", score: 8.2 },
    { title: "极限竞速：地平线2", score: 9.2 },
    { title: "中土世界：暗影魔多", score: 8.9 },
    { title: "异形：隔离", score: 9.0 },
    { title: "看门狗", score: 8.4 },
    { title: "泰坦陨落", score: 8.8 },
    { title: "FIFA 15", score: 8.7 },
    { title: "NBA 2K15", score: 8.6 },
  ],
  "2015": [
    { title: "巫师3：狂猎", score: 9.8 },
    { title: "辐射4", score: 9.2 },
    { title: "血源诅咒", score: 9.3 },
    { title: "合金装备5：幻痛", score: 9.1 },
    { title: "使命召唤：黑色行动3", score: 8.5 },
    { title: "星球大战：前线", score: 8.3 },
    { title: "蝙蝠侠：阿卡姆骑士", score: 8.9 },
    { title: "超级马里奥制造", score: 9.0 },
    { title: "火箭联盟", score: 9.2 },
    { title: "生命奇迹", score: 8.7 },
    { title: "FIFA 16", score: 8.6 },
    { title: "NBA 2K16", score: 8.8 },
  ],
  "2016": [
    { title: "神秘海域4：盗贼末路", score: 9.3 },
    { title: "黑暗之魂3", score: 9.2 },
    { title: "守望先锋", score: 9.4 },
    { title: "战争机器4", score: 8.9 },
    { title: "战地1", score: 9.0 },
    { title: "泰坦陨落2", score: 9.1 },
    { title: "最终幻想15", score: 8.7 },
    { title: "文明6", score: 9.0 },
    { title: "杀手", score: 8.8 },
    { title: "使命召唤：无限战争", score: 8.2 },
    { title: "FIFA 17", score: 8.7 },
    { title: "NBA 2K17", score: 8.9 },
  ],
  "2017": [
    { title: "塞尔达传说：旷野之息", score: 9.9 },
    { title: "超级马里奥：奥德赛", score: 9.7 },
    { title: "地平线：零之黎明", score: 9.3 },
    { title: "尼尔：机械纪元", score: 9.2 },
    { title: "女神异闻录5", score: 9.4 },
    { title: "刺客信条：起源", score: 9.0 },
    { title: "使命召唤：二战", score: 8.5 },
    { title: "命运2", score: 8.6 },
    { title: "生化危机7", score: 8.9 },
    { title: "极限竞速7", score: 9.1 },
    { title: "FIFA 18", score: 8.8 },
    { title: "NBA 2K18", score: 8.7 },
  ],
  "2018": [
    { title: "荒野大镖客：救赎2", score: 9.7 },
    { title: "战神", score: 9.8 },
    { title: "漫威蜘蛛侠", score: 9.2 },
    { title: "怪物猎人：世界", score: 9.1 },
    { title: "刺客信条：奥德赛", score: 8.9 },
    { title: "底特律：变人", score: 8.8 },
    { title: "使命召唤：黑色行动4", score: 8.4 },
    { title: "极限竞速：地平线4", score: 9.3 },
    { title: "古墓丽影：暗影", score: 8.6 },
    { title: "战地5", score: 8.3 },
    { title: "FIFA 19", score: 8.5 },
    { title: "NBA 2K19", score: 8.6 },
  ],
  "2019": [
    { title: "只狼：影逝二度", score: 9.4 },
    { title: "死亡搁浅", score: 8.9 },
    { title: "控制", score: 9.0 },
    { title: "星球大战绝地：陨落的武士团", score: 8.8 },
    { title: "全境封锁2", score: 8.5 },
    { title: "鬼泣5", score: 9.1 },
    { title: "使命召唤：现代战争", score: 8.7 },
    { title: "生化危机2：重制版", score: 9.2 },
    { title: "无主之地3", score: 8.9 },
    { title: "地铁：离去", score: 8.7 },
    { title: "FIFA 20", score: 8.4 },
    { title: "NBA 2K20", score: 8.3 },
  ],
  "2020": [
    { title: "最后生还者2", score: 9.3 },
    { title: "对马岛之魂", score: 9.2 },
    { title: "半条命：爱莉克斯", score: 9.1 },
    { title: "毁灭战士：永恒", score: 9.0 },
    { title: "刺客信条：英灵殿", score: 8.7 },
    { title: "最终幻想7：重制版", score: 9.0 },
    { title: "黑道圣徒：重启版", score: 8.5 },
    { title: "使命召唤：黑色行动冷战", score: 8.4 },
    { title: "赛博朋克2077", score: 8.0 },
    { title: "动物森友会", score: 9.2 },
    { title: "FIFA 21", score: 8.3 },
    { title: "NBA 2K21", score: 8.2 },
  ],
  "2021": [
    { title: "生化危机8：村庄", score: 8.9 },
    { title: "战地2042", score: 7.5 },
    { title: "光环：无限", score: 8.7 },
    { title: "极限竞速：地平线5", score: 9.4 },
    { title: "死亡循环", score: 8.8 },
    { title: "Far Cry 6", score: 8.3 },
    { title: "Ratchet & Clank: Rift Apart", score: 9.0 },
    { title: "返校", score: 8.9 },
    { title: "使命召唤：先锋", score: 8.1 },
    { title: "幽灵线：东京", score: 8.6 },
    { title: "FIFA 22", score: 8.4 },
    { title: "NBA 2K22", score: 8.3 },
  ],
  "2022": [
    { title: "艾尔登法环", score: 9.7 },
    { title: "战神：诸神黄昏", score: 9.5 },
    { title: "地平线：西部禁域", score: 9.1 },
    { title: "使命召唤：现代战争2", score: 8.6 },
    { title: "最终幻想16", score: 8.9 },
    { title: "星空", score: 8.7 },
    { title: "霍格沃茨之遗", score: 8.8 },
    { title: "瘟疫传说：安魂曲", score: 8.9 },
    { title: "索尼克：边境", score: 8.4 },
    { title: "FIFA 23", score: 8.5 },
    { title: "NBA 2K23", score: 8.4 },
    { title: "宝可梦：朱/紫", score: 8.3 },
  ],
  "2023": [
    { title: "塞尔达传说：王国之泪", score: 9.8 },
    { title: "博德之门3", score: 9.6 },
    { title: "漫威蜘蛛侠2", score: 9.3 },
    { title: "最终幻想16", score: 9.0 },
    { title: "星空", score: 8.5 },
    { title: "死亡空间：重制版", score: 9.1 },
    { title: "生化危机4：重制版", score: 9.2 },
    { title: "使命召唤：现代战争3", score: 8.5 },
    { title: "极限竞速：赛道", score: 8.9 },
    { title: "EA Sports FC 24", score: 8.4 },
    { title: "NBA 2K24", score: 8.3 },
    { title: "街头霸王6", score: 9.0 },
  ],
};

export default data;